### ISSUE TITLE
Travis environment variables

### ISSUE THREAD

**Issue by rimonhanna** [jenkinsci/travis-yml-plugin#6]
my .travis.yml file has a few environment variables defined that are not being recognised by fastlane in this case

**Comment by alvarolorentedev** [comment]
hello @rimonhanna can you run your jenkins build with the enviroment variable expressed in the next text.
```
If you have any failure on your build and want to review the final generated, you should declare the environment variable DEBUG_TRAVIS_YML either on your build node or in jenkins.
```
this will retain in your workspace the shell script generated from the `.travis.yml`, with this we can debug a bit more and see if the environment variables are declared correctly.

**Comment by alvarolorentedev** [comment]
as it has been 2 month without any more information this issue is going to be close, let me know if you want it to be reopen in the future when more information is available.
